"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import dj_database_url
from decouple import config as env_config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Pulled from env in real deployments; the hardcoded value here is a
# dev-only fallback so local setup still works without extra config.
SECRET_KEY = env_config(
    'DJANGO_SECRET_KEY',
    default=(
        'django-insecure-6dp-$a0%wq)5i=b11xlb*!34%v*=o8h7f&47j9(w)4!hj3!&yz'
    ),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_config('DJANGO_DEBUG', default=True, cast=bool)

# Django enforces ALLOWED_HOSTS strictly once DEBUG=False — an empty list
# would reject every request in production, not just be "less secure".
# Populate via env var (comma-separated) when DEBUG is off.
ALLOWED_HOSTS = (
    [host.strip() for host in env_config('DJANGO_ALLOWED_HOSTS', default='').split(',') if host.strip()]
    if not DEBUG else []
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    "rest_framework_simplejwt",
    'corsheaders',
    'api.apps.ApiConfig',
]

# BrowsableAPIRenderer is handy in dev but exposes a full HTML explorer
# (including POST/PUT forms) in production — gate it on DEBUG.
_DEFAULT_RENDERER_CLASSES = ['rest_framework.renderers.JSONRenderer']
if DEBUG:
    _DEFAULT_RENDERER_CLASSES.append('rest_framework.renderers.BrowsableAPIRenderer')

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    # REQUIRED alongside DEFAULT_THROTTLE_CLASSES above — without rates
    # for the 'anon'/'user' scopes, SimpleRateThrottle.get_rate() raises
    # ImproperlyConfigured on every single request, since both throttle
    # classes are applied globally and instantiated on every call.
    # Tune these numbers to real expected traffic.
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
    },
    "DEFAULT_AUTHENTICATION_CLASSES": [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticatedOrReadOnly"],
    "DEFAULT_RENDERER_CLASSES": _DEFAULT_RENDERER_CLASSES,
    "DEFAULT_PARSER_CLASSES": [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

# Access/refresh token lifetimes and rotation policy for
# rest_framework_simplejwt. Defaults (5 min access / 1 day refresh, no
# rotation) apply silently if this dict is absent — made explicit here,
# and refresh-token rotation is on so a compromised or post-deletion
# refresh token can't keep minting new access tokens indefinitely.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    # BLACKLIST_AFTER_ROTATION requires adding
    # 'rest_framework_simplejwt.token_blacklist' to INSTALLED_APPS and
    # running its migrations. Left off here since that app isn't
    # installed yet — add both together if you want it.
    "BLACKLIST_AFTER_ROTATION": False,
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
]
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (user uploads, e.g. UserProfile.avatar)
# https://docs.djangoproject.com/en/6.0/topics/files/
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
DATABASE_URL = env_config('DATABASE_URL', default='')
DATABASE_CONFIG = (
    dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=0,
        ssl_require=True,
    )
    if DATABASE_URL else {}
)

# Use the hosted database when DATABASE_URL is exported; otherwise keep local
# Django commands usable with the repository's SQLite database.
if DATABASE_CONFIG:
    DATABASES = {'default': DATABASE_CONFIG}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }